---
data_model: ensemble
fit_model: ensemble
t: 8
theta: 1
use_ratio: yes
signal_noise_ratio: 
- 0.6
- 0.65
sigma.f: 1
sigma.s: 1
p.s: 0.5
y0: 0
B: 20  # number of batches
R: 250 # number of reps per batch
d: 1000
L: 
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
save_draws?: no
save_all_time_steps?: no
save_pre_adj_draws?: no
save_all_pre_adj_time_steps?: no
save_candidate_draws?: no
...
