---
data_model: arima_model
fit_model: arima_model
t: 
  - 8
theta: 1
naive_mods:
  use_ratio: no
  signal_noise_ratio: 0.25
  sigma.f: 1
  sigma.s: 0
simple_lm:
  beta0: 
    - 0
  beta1:
    - 2
  sigma: 
    - 1
    - 2
ar_simple_lm:
  beta0: 0
  beta1: 2
  beta2: 1
  sigma: 1
arima_model:
  phi: 0.7
  mu: 
    - 0
    - -0.2
  sigma: 
    - 0
    - 0.5
p.s: 0
y0: 0
B: 1
R: 250
d: 1000
L: 40
...
