---
data_model: simple_lm
fit_model: simple_lm
t: 14
theta: 1
use_ratio: no
signal_noise_ratio: 0.25
sigma.f: 1
sigma.s: 0
linear_mod:
  beta1:
    - -1 
    - 0.5
    - 1
    - 1.5
    - 2
ar_linear_mod:
  beta1: 1
  beta2: 1
p.s: 0
y0: 0
B: 20
R: 250
d: 1000
L: 40
...
